#Example:	decode_table.c main.c decodeHeader.h
#	gcc decode_table.c main.c decodeHeader.h -o Example
Example:	encode.c encodeHeader.h decode_table.c
	gcc encode.c encodeHeader.h decode_table.c -o Example
